version: '3.8'

services:
  valuator:
    container_name: valuator
    build:
      context: ./microservices/valuator
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8082:8082"
    networks:
      - app-network
    depends_on:
      redis:
        condition: service_healthy


  redis:
    image: redis:latest
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data:
  redis_data: