version: '3.8'

services:
  centrifugo:
    image: centrifugo/centrifugo:latest
    container_name: centrifugo
    restart: always
    ports:
      - "8000:8000"
      - "3000:3000"
    environment:
      - CENTRIFUGO_ADMIN_PASSWORD=admin_password
      - CENTRIFUGO_ADMIN_SECRET=admin_secret
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./centrifugo/config.json:/centrifugo/config.json

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - app-network
    depends_on:
      valuator1:
        condition: service_healthy
      valuator2:
        condition: service_healthy

  valuator1:
    container_name: valuator1
    build:
      context: ./microservices/valuator
      dockerfile: Dockerfile
    environment:
      PORT: 5001
      DB_MAIN: redis-main:6379
      DB_RU: redis-ru:6379
      DB_EU: redis-eu:6379
      DB_ASIA: redis-asia:6379
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:5001/health"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      redis-main:
        condition: service_healthy
      rabbit:
        condition: service_healthy

  valuator2:
    container_name: valuator2
    build:
      context: ./microservices/valuator
      dockerfile: Dockerfile
    environment:
      PORT: 5002
    networks:
      - app-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:5002/health"]
      interval: 1s
      timeout: 2s
      retries: 3
      start_period: 5s
    depends_on:
      redis-main:
        condition: service_healthy
      rabbit:
        condition: service_healthy

  calculator:
    container_name: calculator
    build:
      context: ./microservices/rankcalculator
      dockerfile: Dockerfile
    networks:
      - app-network
    depends_on:
      redis-main:
        condition: service_healthy
      rabbit:
        condition: service_healthy

  eventslogger:
    container_name: eventslogger
    build:
      context: ./microservices/eventslogger
      dockerfile: Dockerfile
    networks:
      - app-network
    depends_on:
      redis-main:
        condition: service_healthy
      rabbit:
        condition: service_healthy

  redis-main:
    image: redis:latest
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      redis-ru:
        condition: service_healthy
      redis-eu:
        condition: service_healthy
      redis-asia:
        condition: service_healthy
    networks:
      - app-network

  redis-ru:
    image: redis:latest
    ports:
      - "127.0.0.1:6378:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-network

  redis-eu:
    image: redis:latest
    ports:
      - "127.0.0.1:6377:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-network

  redis-asia:
    image: redis:latest
    ports:
      - "127.0.0.1:6376:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-network

  rabbit:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - app-network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  app-network:

volumes:
  redis_data:
  rabbitmq_data: